### ISSUE TITLE
如何修改标题样式

### ISSUE THREAD

**Issue by BrightSoulXYHY** [ksky521/mpeditor#11]
麻烦请问一下应该如何修改标题的样式，想修改一下标题的字体字号啥的，但没学过前端能不能提供一点帮助

**Comment by JeremyWu917** [comment]
@BrightSoulXYHY 
在此文件夹修改 `src\css\preview.less`，修改完重新构建，在本地运行再编辑就可以了 ☕ 
```css
    h1,
    h2,
    h3,
    h4,
    h5,
    h6 {
        margin: 12px 0 8px;
        font-weight: bold;
        color: @title-color;
    }
    h1 {
        line-height: 1.75;
        font-size: 1.2em;
        font-weight: 600;
        margin: 1.75em auto 0.5em;
        text-align: center;
        background-color: #303133;
        color: #fff;
        display: table;
        padding: 0 1em;
    }

    h2 {
        line-height: 1.75;
        font-size: 1.2em;
        font-weight: 600;
        margin: 1.5em auto 0.5em;
    }

    h3 {
        border-left: 3px solid @color-primary;
        text-align: left;
        padding-left: 10px;
        font-size: 1.1em;
        font-weight: 600;
        margin: 1.5em 8px 0.5em 0;
    }
    h4 {
        font-size: 16px;
        color: #666;
        font-weight: 600;
    }
    h5 {
        font-size: 18px;
        font-weight: bold;
        min-height: 32px;
        line-height: 28px;
        border-bottom: solid 1px @title-color;
        color: @title-color;
        display: inline-block;
        margin: 12px auto;
        padding: 0.5 * @def-font-size 0 0;
        text-align: center;
        width: 80%;
        display: flex;
        flex-direction: column;
        justify-content: center;
    }
    h6 {
        font-size: 18px;
        border-bottom: solid 1px @title-color;
        margin-bottom: 10px;
    }
```
